Added prime eligibility functionality.
AsaCapstone2016/asa pull request #56
Opened 2016-11-22 15:21 UTC by moraneva

Amazon seems to be pretty indecisive on whether an item if prime or not but it's better than nothing. Have it working now for item search and variations. Haven't added into variation summary yet but we could look into doing that.

2016-11-23 03:20 UTC, arockett requested changes
See my comment in the isItemPrimeEligible function for what to change

2016-11-23 03:20 UTC, becketta commented on core/amazon/index.js
> +        let isPrime = false;
I'd prefer if you didn't mix styles here... either use the following if-else statement to set the isPrime variable which you always return at the end or just return true or false from inside the if-else statement whenever you want. Right now you use both methods

2016-11-23 20:51 UTC, moraneva commented on core/amazon/index.js
> +        let isPrime = false;
show be good now.

2016-11-27 00:43 UTC, arockett approved these changes

2016-11-27 00:44 UTC, merged